### ISSUE TITLE
Project access

### ISSUE THREAD

**Issue by khaninger** [hunissweet/Soft_finger_training#1]
Hi Hun acn you please add me to the repo so I can push to another branch?

**Comment by hunissweet** [comment]
Hello Kevin! Now I am trying to get into the Team online meeting. If you are waiting for me, could you give me an access to get into the meeting? Or Send me the link again!

Thanks
Hun 
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-05-08 (수) 18:06:56 (GMT+09:00)
Subject: [hunissweet/Soft_finger_training] Project access (Issue #1)

Hi Hun acn you please add me to the repo so I can push to another branch?
